### ISSUE TITLE
error

### ISSUE THREAD

**Issue by www516717402** [mcesar-rlacruz/typora-compact#1]
in MacOS, this theam cant show completly. Color is white in current typora.

**Comment by mcesar-rlacruz** [comment]
Hi,

Unfortunately I do not have the means to check anything in MacOS. A pity as I think that the user base for Typora is bigger in it that in Windows.

I suppose it will be something related to fonts but, as said, I cannot check anything in MacOS, sorry.

Regards.

**Comment by mcesar-rlacruz** [comment]
Hi again,

In spite of my previous post, I was finally able to test the Compact theme for Typora in macOS Big Sur (11.2.3). It worked as expected, not needing any modification to the usual installation mechanism for Typora themes. Thus, I need more info in order to try to replicate the issue.

Incidentally, I tried not to copy the fonts folder (in case it was your problem), but it kept working, as Typora accessed Google fonts to download them, so this was not the culprit.

Incidentally 2, I was also able to check it upon Linux (Ubuntu), also working as expected.

Regards.

**Comment by www516717402** [comment]
Thank you for rely. Great help.
